# Generated by Django 4.2.7 on 2023-11-22 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('named_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя URL')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tree_menu.menu', verbose_name='Родительская ветка')),
            ],
            options={
                'verbose_name_plural': 'Меню',
            },
        ),
    ]
